# Generated by Django 3.1.dev20191121095405 on 2020-01-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predicciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='beneficios',
            name='capital_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='beneficios',
            name='ganancias_brutas',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='beneficios',
            name='ganancias_netas',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='beneficios',
            name='porcentaje_beneficio',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
