# Generated by Django 3.1.dev20191121095405 on 2020-01-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20200122_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicciones',
            name='ejecucion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predicciones',
            name='resultado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='predicciones',
            name='prediction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
