# Generated by Django 3.0.3 on 2020-02-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_beneficios_porcentaje_beneficio_frente_al_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('resultado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cuotaEmpate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ejecucion', models.IntegerField(default=0)),
            ],
        ),
    ]
