# Generated by Django 3.0.3 on 2020-02-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0007_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficios',
            name='temporada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historico',
            name='temporada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predicciones',
            name='temporada',
            field=models.IntegerField(default=0),
        ),
    ]
