# Generated by Django 3.0.3 on 2020-02-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0011_predicciones_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='probabilidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
