# Generated by Django 3.0.3 on 2020-02-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0012_historico_probabilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiosmes',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='beneficiosmes',
            name='porcentaje_beneficio',
        ),
        migrations.RemoveField(
            model_name='beneficiosmes',
            name='porcentaje_beneficio_frente_al_inicial',
        ),
    ]
